Repository ukayaj620/batikcomp, pull requests merged in 2020-11, with the labels that each got.

#2 feat: create invers and binarization flowchart
  flowchart/.drawio/Binarization.drawio
  flowchart/.drawio/Invers.drawio
  flowchart/.png/Binarization.png
  flowchart/.png/Invers.png
  main.lfm
  main.pas
Labels: enhancement

#4 docs: add paddingBitmap and Convolution function flowchart
  flowchart/.drawio/Convolution.drawio
  flowchart/.drawio/PaddingBitmap.drawio
  flowchart/.png/Convolution.png
  flowchart/.png/PaddingBitmap.png
Labels: documentation

#5 docs: arithmeticAnd and arithmeticAddition flowchart
  flowchart/.drawio/ArithmeticAddition.drawio
  flowchart/.drawio/ArithmeticAdditionColor.drawio
  flowchart/.drawio/ArithmeticAdditionColor_Gray.drawio
  flowchart/.drawio/ArithmeticAnd.drawio
  flowchart/.png/ArithmeticAddition.png
  flowchart/.png/ArithmeticAdditionColor.png
  flowchart/.png/ArithmeticAdditionColor_Gray.png
  flowchart/.png/ArithmeticAnd.png
Labels: documentation

#6 docs: add documentation for constraints flowchart
  flowchart/.drawio/Constraints.drawio
  flowchart/.drawio/Grayscaling.drawio
  flowchart/.png/Constraints.png
  flowchart/.png/Grayscaling.png
Labels: documentation

#7 docs: add arithmetic multiply flowchart
  flowchart/.drawio/ArithmeticMultiply.drawio
  flowchart/.png/ArithmeticMultiply.png
Labels: documentation

#8 docs: add example assets image for testing purpose
  images/Nature_Tab_Assets/Background.bmp
  images/Nature_Tab_Assets/Pattern_1.bmp
  images/Nature_Tab_Assets/Pattern_2.bmp
  images/Nature_Tab_Assets/Pattern_Object.bmp
  images/Nature_Tab_Assets/Texture.bmp
  images/Pattern_Tab_Assets/Background_1.bmp
  images/Pattern_Tab_Assets/Background_2.bmp
  images/Pattern_Tab_Assets/Background_3.bmp
  images/Pattern_Tab_Assets/Pattern.bmp
  images/Pattern_Tab_Assets/Pattern_Object.bmp
  images/Pattern_Tab_Assets/Texture.bmp
Labels: documentation

#9 feat: add additional radio group to set the patter 1 pipeline process
  backup/batikcomp.lps
  batikcomp.lps
  images/Nature_Tab_Assets/Result.bmp
  images/Pattern_Tab_Assets/Result.bmp
  lib/i386-win32/batikcomp.or
  lib/i386-win32/main.lfm
  lib/i386-win32/main.o
  lib/i386-win32/main.ppu
  main.lfm
  main.pas
Labels: enhancement

#10 update flowchart documentation, code refactoring
  batikcomp.lps
  flowchart/.drawio/BoolToByte.drawio
  flowchart/.drawio/CompassKernel.drawio
  flowchart/.drawio/Convolution.drawio
  flowchart/.drawio/Dilation.drawio
  flowchart/.drawio/EdgeDetection.drawio
  flowchart/.drawio/Erosion.drawio
  flowchart/.png/BoolToByte.png
  flowchart/.png/CompassKernel.png
  flowchart/.png/Convolution.png
  flowchart/.png/Dilation.png
  flowchart/.png/EdgeDetection.png
  flowchart/.png/Erosion.png
  lib/i386-win32/main.o
  lib/i386-win32/main.ppu
  main.pas
Labels: documentation, enhancement

#11 docs: add binary to grayscale to flowchart
  flowchart/.drawio/ArithmeticAdditionColor_Gray.drawio
  flowchart/.drawio/BinaryToGrayscale.drawio
  flowchart/.png/ArithmeticAdditionColor_Gray.png
  flowchart/.png/BinaryToGrayscale.png
Labels: documentation

#12 update docs, refactor code variable naming
  backup/batikcomp.lps
  batikcomp.lps
  flowchart/.drawio/ImageProcessingPipeline.drawio
  flowchart/.png/ImageProcessingPipeline.png
  images/Background.bmp
  images/Bunga_1.bmp
  images/Bunga_2.bmp
  images/Ceramic.bmp
  images/Nature_Tab_Assets/Result.bmp
  images/Pattern_Object_1.bmp
  images/Pattern_Object_2.bmp
  images/Pattern_Tab_Assets/Background_1.bmp
  images/Pattern_Tab_Assets/Background_2.bmp
  images/Pattern_Tab_Assets/Background_3.bmp
  images/Pattern_Tab_Assets/Result.bmp
  images/Pattern_Tab_Assets/Texture.bmp
  images/Texture.bmp
  images/UBM.bmp
  lib/i386-win32/batikcomp.or
  lib/i386-win32/main.lfm
  lib/i386-win32/main.o
  lib/i386-win32/main.ppu
  main.lfm
  main.pas
Labels: documentation, enhancement

#13 doc: added ShowImageForm and InitImageBitmap flowcharts
  flowchart/.drawio/InitImageBitmap.drawio
  flowchart/.drawio/ShowImageFromBitmap Binary.drawio
  flowchart/.drawio/ShowImageFromBitmap Color.drawio
  flowchart/.drawio/ShowImageFromBitmap Grayscale.drawio
  flowchart/.png/InitImageBitmap.png
  flowchart/.png/ShowImageFromBitmap Binary.png
  flowchart/.png/ShowImageFromBitmap Color.png
  flowchart/.png/ShowImageFromBitmap Grayscale.png
Labels: documentation
